version: '3'
services:
  server:
    build: .
    volumes: 
      - .:/go/src/project
    env_file: 
      - ./.env
    ports:
      - "${API_PORT}:${API_PORT}"
    entrypoint: ./docker_compose_entrypoint.sh